import { json, type ActionFunctionArgs } from "@remix-run/node";
import { authenticate } from "../shopify.server";
import { Resend } from "resend";
import * as XLSX from "xlsx";
import puppeteer from "puppeteer";
import prisma from "../db.server";

// ── Severity helpers ──────────────────────────────────────────────────────────

function severityColor(s: string) {
  if (s === "High") return "#d72c0d";
  if (s === "Medium") return "#b98900";
  return "#637381";
}

function severityBg(s: string) {
  if (s === "High") return "#fef2f2";
  if (s === "Medium") return "#fffbeb";
  return "#f0f9ff";
}

// ── Excel builder ─────────────────────────────────────────────────────────────

function buildExcel(scan: any, storeName: string): Buffer {
  const result = scan.result as any;
  const summary = result?.scan_summary || {};
  const wb = XLSX.utils.book_new();

  // Summary sheet
  const summaryData = [
    ["Store GMC Compliance Report — ShopFlix AI"],
    [],
    ["Store Name", storeName],
    ["Store URL", summary.store_url || ""],
    ["Overall Risk", summary.overall_risk || ""],
    ["Pages Scanned", summary.pages_scanned ?? ""],
    ["Missing Required Pages", summary.pages_missing ?? ""],
    ["Broken Links Found", summary.broken_links_found ?? ""],
    ["Scan Date", new Date(scan.updatedAt).toLocaleString()],
    ["Generated By", "ShopFlix AI (shopflixai.com)"],
  ];
  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
  summarySheet["!cols"] = [{ wch: 28 }, { wch: 60 }];
  XLSX.utils.book_append_sheet(wb, summarySheet, "Summary");

  const addSheet = (sheetName: string, issues: any[]) => {
    if (!issues?.length) return;
    const headers = ["#", "Severity", "Issue Description", "Suggested Fix", "Fix Steps", "Auto Fixable", "Credit Cost"];
    const rows = issues.map((issue: any, i: number) => [
      i + 1,
      issue.severity || "",
      issue.issue_description || issue.label || issue.url || "",
      issue.suggested_fix || "",
      Array.isArray(issue.detailed_fix_steps) ? issue.detailed_fix_steps.join("\n") : "",
      issue.auto_fixable ? "Yes" : "No",
      issue.credit_cost ?? "",
    ]);
    const ws = XLSX.utils.aoa_to_sheet([headers, ...rows]);
    ws["!cols"] = [{ wch: 4 }, { wch: 10 }, { wch: 50 }, { wch: 40 }, { wch: 60 }, { wch: 12 }, { wch: 10 }];
    XLSX.utils.book_append_sheet(wb, ws, sheetName);
  };

  if (result?.missing_pages?.length) {
    const headers = ["#", "Page", "URL", "Severity", "Suggested Fix", "Fix Steps"];
    const rows = result.missing_pages.map((p: any, i: number) => [
      i + 1, p.label || "", p.url || "", p.severity || "High",
      p.suggested_fix || "",
      Array.isArray(p.detailed_fix_steps) ? p.detailed_fix_steps.join("\n") : "",
    ]);
    const ws = XLSX.utils.aoa_to_sheet([headers, ...rows]);
    ws["!cols"] = [{ wch: 4 }, { wch: 22 }, { wch: 40 }, { wch: 10 }, { wch: 40 }, { wch: 60 }];
    XLSX.utils.book_append_sheet(wb, ws, "Missing Pages");
  }

  if (result?.broken_links?.length) {
    const headers = ["#", "URL", "Severity", "Suggested Fix"];
    const rows = result.broken_links.map((l: any, i: number) => [i + 1, l.url || "", "High", l.suggested_fix || ""]);
    const ws = XLSX.utils.aoa_to_sheet([headers, ...rows]);
    ws["!cols"] = [{ wch: 4 }, { wch: 50 }, { wch: 10 }, { wch: 50 }];
    XLSX.utils.book_append_sheet(wb, ws, "Broken Links");
  }

  addSheet("GMC Compliance", result?.merchant_center_compliance);
  addSheet("Customer Trust & Policy", result?.customer_trust_and_policy);
  addSheet("Site Structure & SEO", result?.site_structure_and_seo);

  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
}

// ── PDF builder (via Puppeteer) ───────────────────────────────────────────────

function buildPdfHtml(scan: any, storeUrl: string, storeName: string): string {
  const result = scan.result as any;
  const summary = result?.scan_summary || {};
  const riskColor = summary.overall_risk === "High" ? "#d72c0d" : summary.overall_risk === "Medium" ? "#b98900" : "#12a04a";

  const issueRows = (issues: any[]) =>
    (issues || []).map((issue: any) => `
      <div style="border-left:3px solid ${severityColor(issue.severity||"Low")};padding:8px 12px;margin-bottom:10px;background:#fafafa;border-radius:0 4px 4px 0">
        <div style="display:flex;gap:8px;align-items:flex-start;margin-bottom:4px">
          <span style="padding:2px 7px;border-radius:4px;font-size:10px;font-weight:700;background:${severityBg(issue.severity||"")};color:${severityColor(issue.severity||"")};white-space:nowrap;flex-shrink:0">${issue.severity||""}</span>
          <span style="font-size:13px;color:#212121;line-height:1.5">${issue.issue_description||issue.label||issue.url||""}</span>
        </div>
        ${issue.suggested_fix ? `<p style="margin:4px 0 0 12px;font-size:12px;color:#555">💡 ${issue.suggested_fix}</p>` : ""}
        ${Array.isArray(issue.detailed_fix_steps) && issue.detailed_fix_steps.length ? `
          <ol style="margin:6px 0 0 12px;padding-left:16px;font-size:11px;color:#555;line-height:1.7">
            ${issue.detailed_fix_steps.map((s: string) => `<li>${s}</li>`).join("")}
          </ol>` : ""}
      </div>`).join("");

  const section = (title: string, issues: any[]) => `
    <div style="margin-bottom:24px;page-break-inside:avoid">
      <h3 style="margin:0 0 10px 0;font-size:14px;font-weight:700;color:#1a4a5a;border-bottom:2px solid #e5e7eb;padding-bottom:6px;text-transform:uppercase;letter-spacing:0.5px">${title}</h3>
      ${(issues||[]).length === 0
        ? `<p style="color:#12a04a;font-size:13px;margin:0">✓ No issues found in this category.</p>`
        : issueRows(issues)}
    </div>`;

  const totalIssues =
    (result?.missing_pages?.length || 0) +
    (result?.broken_links?.length || 0) +
    (result?.merchant_center_compliance?.length || 0) +
    (result?.customer_trust_and_policy?.length || 0) +
    (result?.site_structure_and_seo?.length || 0);

  const highCount = [...(result?.missing_pages||[]), ...(result?.broken_links||[]),
    ...(result?.merchant_center_compliance||[]), ...(result?.customer_trust_and_policy||[]),
    ...(result?.site_structure_and_seo||[])].filter((i: any) => i.severity === "High").length;

  const medCount = [...(result?.missing_pages||[]), ...(result?.broken_links||[]),
    ...(result?.merchant_center_compliance||[]), ...(result?.customer_trust_and_policy||[]),
    ...(result?.site_structure_and_seo||[])].filter((i: any) => i.severity === "Medium").length;

  return `<!DOCTYPE html><html><head><meta charset="utf-8">
  <title>GMC Compliance Report — ${storeName}</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 32px; color: #212121; font-size: 13px; background: white; }
    @media print { body { padding: 16px; } }
  </style>
</head><body>
  <!-- Header -->
  <div style="background:linear-gradient(135deg,#1a4a5a,#2A5B6D);padding:28px 32px;border-radius:10px;margin-bottom:24px;color:white">
    <div style="display:flex;justify-content:space-between;align-items:flex-start">
      <div>
        <p style="margin:0 0 4px 0;font-size:11px;opacity:0.7;text-transform:uppercase;letter-spacing:1px">ShopFlix AI — Store Compliance</p>
        <h1 style="margin:0 0 6px 0;font-size:22px;font-weight:700">GMC Compliance Report</h1>
        <p style="margin:0;font-size:13px;opacity:0.85">${storeName} · ${storeUrl}</p>
      </div>
      <div style="text-align:right">
        <p style="margin:0 0 2px 0;font-size:11px;opacity:0.7">Scanned</p>
        <p style="margin:0;font-size:13px;font-weight:600">${new Date(scan.updatedAt).toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" })}</p>
      </div>
    </div>
  </div>

  <!-- Summary cards -->
  <div style="display:flex;gap:12px;margin-bottom:24px;flex-wrap:wrap">
    <div style="flex:1;min-width:120px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:14px 16px">
      <p style="margin:0 0 4px 0;font-size:10px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:0.5px">Overall Risk</p>
      <p style="margin:0;font-size:22px;font-weight:700;color:${riskColor}">${summary.overall_risk || "—"}</p>
    </div>
    <div style="flex:1;min-width:120px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:14px 16px">
      <p style="margin:0 0 4px 0;font-size:10px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:0.5px">Total Issues</p>
      <p style="margin:0;font-size:22px;font-weight:700;color:${totalIssues > 0 ? "#d72c0d" : "#12a04a"}">${totalIssues}</p>
    </div>
    <div style="flex:1;min-width:120px;background:#fef2f2;border:1px solid #fca5a5;border-radius:8px;padding:14px 16px">
      <p style="margin:0 0 4px 0;font-size:10px;color:#d72c0d;font-weight:600;text-transform:uppercase;letter-spacing:0.5px">High Severity</p>
      <p style="margin:0;font-size:22px;font-weight:700;color:#d72c0d">${highCount}</p>
    </div>
    <div style="flex:1;min-width:120px;background:#fffbeb;border:1px solid #fcd34d;border-radius:8px;padding:14px 16px">
      <p style="margin:0 0 4px 0;font-size:10px;color:#b98900;font-weight:600;text-transform:uppercase;letter-spacing:0.5px">Medium Severity</p>
      <p style="margin:0;font-size:22px;font-weight:700;color:#b98900">${medCount}</p>
    </div>
    <div style="flex:1;min-width:120px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:14px 16px">
      <p style="margin:0 0 4px 0;font-size:10px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:0.5px">Pages Scanned</p>
      <p style="margin:0;font-size:22px;font-weight:700">${summary.pages_scanned ?? "—"}</p>
    </div>
    <div style="flex:1;min-width:120px;background:${summary.pages_missing > 0 ? "#fef2f2" : "#f0fdf4"};border:1px solid ${summary.pages_missing > 0 ? "#fca5a5" : "#86efac"};border-radius:8px;padding:14px 16px">
      <p style="margin:0 0 4px 0;font-size:10px;color:${summary.pages_missing > 0 ? "#d72c0d" : "#12a04a"};font-weight:600;text-transform:uppercase;letter-spacing:0.5px">Missing Pages</p>
      <p style="margin:0;font-size:22px;font-weight:700;color:${summary.pages_missing > 0 ? "#d72c0d" : "#12a04a"}">${summary.pages_missing ?? "—"}</p>
    </div>
  </div>

  <!-- What this means -->
  <div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;padding:16px 20px;margin-bottom:24px">
    <h3 style="margin:0 0 8px 0;font-size:13px;font-weight:700;color:#1e40af">📋 What This Report Means</h3>
    <p style="margin:0;font-size:12px;color:#1e3a8a;line-height:1.6">
      This report audits <strong>${storeName}</strong> against Google Merchant Center (GMC) requirements, Google Ads landing page policies,
      and e-commerce best practices. Issues marked <strong>High</strong> risk immediate attention and may cause GMC disapproval or ad suspension.
      <strong>Medium</strong> issues affect trust and SEO. <strong>Low</strong> issues are best-practice improvements.
      Use the ShopFlix AI app to auto-fix eligible issues with one click.
    </p>
  </div>

  ${result?.missing_pages?.length ? section("🚫 Missing Required Pages", result.missing_pages.map((p: any) => ({
    severity: p.severity || "High",
    issue_description: `${p.label} — ${p.url}`,
    suggested_fix: p.suggested_fix,
    detailed_fix_steps: p.detailed_fix_steps,
  }))) : ""}
  ${result?.broken_links?.length ? section("🔗 Broken Links", result.broken_links.map((l: any) => ({
    severity: "High",
    issue_description: l.url,
    suggested_fix: l.suggested_fix,
    detailed_fix_steps: l.detailed_fix_steps,
  }))) : ""}
  ${section("🏪 Google Merchant Center Compliance", result?.merchant_center_compliance)}
  ${section("🔒 Customer Trust & Policy Pages", result?.customer_trust_and_policy)}
  ${section("🔍 Site Structure & SEO", result?.site_structure_and_seo)}

  <!-- Footer -->
  <div style="border-top:1px solid #e5e7eb;padding-top:16px;margin-top:8px;display:flex;justify-content:space-between;align-items:center">
    <p style="margin:0;font-size:11px;color:#9ca3af">Generated by ShopFlix AI · shopflixai.com</p>
    <p style="margin:0;font-size:11px;color:#9ca3af">${new Date().toLocaleString()}</p>
  </div>
</body></html>`;
}

async function generatePdf(html: string): Promise<Buffer> {
  const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"],
  });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    const pdf = await page.pdf({
      format: "A4",
      margin: { top: "16px", right: "16px", bottom: "16px", left: "16px" },
      printBackground: true,
    });
    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}

// ── Email body HTML ───────────────────────────────────────────────────────────

function buildEmailBody(scan: any, storeUrl: string, storeName: string): string {
  const result = scan.result as any;
  const summary = result?.scan_summary || {};
  const riskColor = summary.overall_risk === "High" ? "#d72c0d" : summary.overall_risk === "Medium" ? "#b98900" : "#12a04a";
  const riskBg = summary.overall_risk === "High" ? "#fef2f2" : summary.overall_risk === "Medium" ? "#fffbeb" : "#f0fdf4";
  const scannedDate = new Date(scan.updatedAt).toLocaleString();

  const totalIssues =
    (result?.missing_pages?.length || 0) +
    (result?.broken_links?.length || 0) +
    (result?.merchant_center_compliance?.length || 0) +
    (result?.customer_trust_and_policy?.length || 0) +
    (result?.site_structure_and_seo?.length || 0);

  const highCount = [...(result?.missing_pages||[]), ...(result?.broken_links||[]),
    ...(result?.merchant_center_compliance||[]), ...(result?.customer_trust_and_policy||[]),
    ...(result?.site_structure_and_seo||[])].filter((i: any) => i.severity === "High").length;

  // Top issues list (up to 5 high severity)
  const allIssues = [
    ...(result?.missing_pages||[]).map((p: any) => ({ ...p, issue_description: `${p.label} — ${p.url}`, severity: p.severity || "High" })),
    ...(result?.broken_links||[]).map((l: any) => ({ ...l, issue_description: l.url, severity: "High" })),
    ...(result?.merchant_center_compliance||[]),
    ...(result?.customer_trust_and_policy||[]),
    ...(result?.site_structure_and_seo||[]),
  ];
  const topIssues = allIssues.filter((i: any) => i.severity === "High").slice(0, 5);

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif">
<div style="max-width:620px;margin:0 auto;padding:32px 16px">

  <!-- Header -->
  <div style="background:linear-gradient(135deg,#1a4a5a 0%,#2A5B6D 100%);border-radius:12px;padding:32px;margin-bottom:20px;text-align:center">
    <div style="font-size:40px;margin-bottom:10px">🛡️</div>
    <h1 style="margin:0 0 6px 0;color:white;font-size:22px;font-weight:700">Store GMC Compliance Report</h1>
    <p style="margin:0;color:rgba(255,255,255,0.8);font-size:13px">${storeName} · ${storeUrl}</p>
  </div>

  <!-- Greeting -->
  <div style="background:white;border-radius:10px;border:1px solid #e5e7eb;padding:24px;margin-bottom:16px">
    <p style="margin:0 0 12px 0;font-size:15px;color:#212121;line-height:1.6">Hi there 👋</p>
    <p style="margin:0 0 12px 0;font-size:14px;color:#444;line-height:1.7">
      Your <strong>ShopFlix AI Store Compliance Scan</strong> for <strong>${storeName}</strong> is complete.
      We've audited your store against Google Merchant Center requirements, Google Ads landing page policies,
      and e-commerce trust standards.
    </p>
    <p style="margin:0;font-size:14px;color:#444;line-height:1.7">
      The full detailed report is attached to this email as a <strong>PDF</strong> and <strong>Excel spreadsheet</strong>.
      Please review all highlighted issues — especially the High severity ones — as they may impact your GMC account approval or ad campaigns.
    </p>
  </div>

  <!-- Risk badge + stats -->
  <div style="background:white;border-radius:10px;border:1px solid #e5e7eb;padding:24px;margin-bottom:16px">
    <div style="display:flex;align-items:center;gap:12px;margin-bottom:20px">
      <h3 style="margin:0;font-size:16px;font-weight:700;color:#212121">Scan Summary</h3>
      <span style="padding:4px 12px;border-radius:20px;font-size:12px;font-weight:700;color:${riskColor};background:${riskBg};border:1px solid ${riskColor}">${summary.overall_risk || "—"} Risk</span>
    </div>
    <table style="width:100%;border-collapse:collapse;text-align:center">
      <tr>
        <td style="padding:12px 8px;border-right:1px solid #e5e7eb">
          <p style="margin:0 0 4px 0;font-size:10px;color:#999;font-weight:600;text-transform:uppercase;letter-spacing:0.5px">Total Issues</p>
          <p style="margin:0;font-size:26px;font-weight:700;color:${totalIssues > 0 ? "#d72c0d" : "#12a04a"}">${totalIssues}</p>
        </td>
        <td style="padding:12px 8px;border-right:1px solid #e5e7eb">
          <p style="margin:0 0 4px 0;font-size:10px;color:#999;font-weight:600;text-transform:uppercase;letter-spacing:0.5px">High Severity</p>
          <p style="margin:0;font-size:26px;font-weight:700;color:#d72c0d">${highCount}</p>
        </td>
        <td style="padding:12px 8px;border-right:1px solid #e5e7eb">
          <p style="margin:0 0 4px 0;font-size:10px;color:#999;font-weight:600;text-transform:uppercase;letter-spacing:0.5px">Pages Scanned</p>
          <p style="margin:0;font-size:26px;font-weight:700;color:#212121">${summary.pages_scanned ?? "—"}</p>
        </td>
        <td style="padding:12px 8px;border-right:1px solid #e5e7eb">
          <p style="margin:0 0 4px 0;font-size:10px;color:#999;font-weight:600;text-transform:uppercase;letter-spacing:0.5px">Missing Pages</p>
          <p style="margin:0;font-size:26px;font-weight:700;color:${summary.pages_missing > 0 ? "#d72c0d" : "#12a04a"}">${summary.pages_missing ?? "—"}</p>
        </td>
        <td style="padding:12px 8px">
          <p style="margin:0 0 4px 0;font-size:10px;color:#999;font-weight:600;text-transform:uppercase;letter-spacing:0.5px">Scanned On</p>
          <p style="margin:0;font-size:12px;font-weight:600;color:#212121">${scannedDate}</p>
        </td>
      </tr>
    </table>
  </div>

  <!-- Top issues -->
  ${topIssues.length > 0 ? `
  <div style="background:white;border-radius:10px;border:1px solid #e5e7eb;padding:24px;margin-bottom:16px">
    <h3 style="margin:0 0 16px 0;font-size:15px;font-weight:700;color:#212121">⚠️ Top Issues Requiring Immediate Attention</h3>
    ${topIssues.map((issue: any) => `
      <div style="border-left:3px solid #d72c0d;padding:10px 14px;margin-bottom:10px;background:#fef2f2;border-radius:0 6px 6px 0">
        <div style="display:flex;align-items:flex-start;gap:8px">
          <span style="display:inline-block;padding:2px 8px;border-radius:4px;font-size:10px;font-weight:700;background:#fef2f2;color:#d72c0d;border:1px solid #fca5a5;flex-shrink:0">HIGH</span>
          <p style="margin:0;font-size:13px;color:#212121;line-height:1.5">${issue.issue_description || ""}</p>
        </div>
        ${issue.suggested_fix ? `<p style="margin:6px 0 0 36px;font-size:12px;color:#666">💡 ${issue.suggested_fix}</p>` : ""}
      </div>`).join("")}
    ${highCount > 5 ? `<p style="margin:12px 0 0 0;font-size:12px;color:#666;font-style:italic">+ ${highCount - 5} more high severity issues in the attached report.</p>` : ""}
  </div>` : ""}

  <!-- CTA -->
  <div style="background:linear-gradient(135deg,#1a4a5a,#2A5B6D);border-radius:10px;padding:24px;margin-bottom:16px;text-align:center">
    <h3 style="margin:0 0 8px 0;color:white;font-size:16px;font-weight:700">Fix Issues Automatically with AI ⚡</h3>
    <p style="margin:0 0 16px 0;color:rgba(255,255,255,0.85);font-size:13px;line-height:1.6">
      Many of these issues can be fixed with a single click inside the ShopFlix AI app —
      including missing policy pages, contact pages, and more.
    </p>
    <a href="https://shopflixai.com" style="display:inline-block;background:white;color:#1a4a5a;padding:10px 28px;border-radius:6px;font-size:14px;font-weight:700;text-decoration:none">
      Open ShopFlix AI →
    </a>
  </div>

  <!-- Attachments note -->
  <div style="background:#f0f9ff;border:1px solid #bae6fd;border-radius:10px;padding:16px 20px;margin-bottom:20px">
    <p style="margin:0;font-size:13px;color:#0369a1;line-height:1.6">
      📎 <strong>Attached to this email:</strong><br>
      • <strong>PDF Report</strong> — Full compliance report with all issues, fix steps, and details<br>
      • <strong>Excel Spreadsheet</strong> — All issues organized by category, sortable and filterable
    </p>
  </div>

  <!-- Footer -->
  <p style="text-align:center;font-size:11px;color:#9ca3af;margin:0">
    Sent by <strong>ShopFlix AI</strong> · <a href="https://shopflixai.com" style="color:#9ca3af">shopflixai.com</a><br>
    You're receiving this because you requested a compliance scan for ${storeName}.
  </p>

</div>
</body>
</html>`;
}

// ── Action ────────────────────────────────────────────────────────────────────

export async function action({ request }: ActionFunctionArgs) {
  const { admin, session } = await authenticate.admin(request);
  if (!session) return json({ error: "Unauthorized" }, { status: 401 });

  const body = await request.json().catch(() => ({}));
  const { scanId } = body as any;

  // Load the scan
  let scan: any;
  try {
    scan = scanId
      ? await (prisma as any).storeScan.findUnique({ where: { id: scanId } })
      : await (prisma as any).storeScan.findFirst({
          where: { shop: session.shop, status: "COMPLETE" },
          orderBy: { createdAt: "desc" },
        });
  } catch (e) {
    return json({ error: "Could not load scan data." }, { status: 500 });
  }

  if (!scan) return json({ error: "No completed scan found." }, { status: 404 });

  // Get shop's registered email + name via Shopify GraphQL
  let shopEmail = "";
  let shopName = session.shop;
  let storeUrl = `https://${session.shop}`;
  try {
    const shopResponse = await admin.graphql(`#graphql
      query shopContact {
        shop { email name primaryDomain { url } }
      }
    `);
    const shopData = await shopResponse.json();
    shopEmail = shopData?.data?.shop?.email || "";
    shopName = shopData?.data?.shop?.name || session.shop;
    storeUrl = shopData?.data?.shop?.primaryDomain?.url || storeUrl;
  } catch (e) {
    console.warn("[store-scan email] Could not fetch shop info:", e);
  }

  if (!shopEmail) {
    return json({ error: "Could not find store email. Please check your Shopify store settings." }, { status: 400 });
  }

  const resendApiKey = process.env.RESEND_API_KEY;
  if (!resendApiKey) {
    return json({ error: "Email service is not configured. Please add RESEND_API_KEY to your .env file." }, { status: 500 });
  }

  const scanStoreUrl = (scan.result as any)?.scan_summary?.store_url || storeUrl;
  const dateStr = new Date(scan.updatedAt).toISOString().split("T")[0];
  const safeStore = shopName.replace(/[^a-z0-9]/gi, "-").toLowerCase();

  // Generate Excel + PDF in parallel
  let excelBuffer: Buffer;
  let pdfBuffer: Buffer;
  try {
    const pdfHtml = buildPdfHtml(scan, scanStoreUrl, shopName);
    [excelBuffer, pdfBuffer] = await Promise.all([
      Promise.resolve(buildExcel(scan, shopName)),
      generatePdf(pdfHtml),
    ]);
  } catch (err: any) {
    console.error("[store-scan email] Attachment generation failed:", err);
    return json({ error: `Failed to generate report attachments: ${err.message}` }, { status: 500 });
  }

  const fromDomain = process.env.RESEND_FROM_EMAIL || "onboarding@resend.dev";
  const resend = new Resend(resendApiKey);

  try {
    const { data, error } = await resend.emails.send({
      from: `ShopFlix AI <${fromDomain}>`,
      to: [shopEmail],
      subject: `Your Store GMC Compliance Report — ${shopName}`,
      html: buildEmailBody(scan, scanStoreUrl, shopName),
      attachments: [
        {
          filename: `compliance-report-${safeStore}-${dateStr}.pdf`,
          content: pdfBuffer.toString("base64"),
          content_type: "application/pdf",
        },
        {
          filename: `compliance-report-${safeStore}-${dateStr}.xlsx`,
          content: excelBuffer.toString("base64"),
          content_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        },
      ],
    });

    if (error) {
      console.error("[store-scan email] Resend error:", error);
      return json({ error: `Failed to send email: ${error.message}` }, { status: 500 });
    }

    console.log("[store-scan email] Sent with attachments, id:", data?.id);
    return json({ success: true, message: `Report sent to ${shopEmail} with PDF & Excel attached.` });
  } catch (err: any) {
    console.error("[store-scan email]", err);
    return json({ error: `Failed to send email: ${err.message}` }, { status: 500 });
  }
}
