import { json, type ActionFunctionArgs } from "@remix-run/node";
import { authenticate } from "../shopify.server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { retryOperation } from "../utils/retry.js";
import { convertMarkdownToHtml } from "../utils/markdown.js";

const genAI = new GoogleGenerativeAI(process.env.GOOGLE_GEMINI_API_KEY!);
const IS_DEVELOPMENT = process.env.NODE_ENV === 'development';

export async function action({ request }: ActionFunctionArgs) {
  const clonedRequest = request.clone();
  const { admin, session } = await authenticate.admin(clonedRequest);
  if (!session) {
    return json({ error: "Unauthorized" }, { status: 401 });
  }

  const { original_product_data, gemini_analysis } = await request.json();

  if (!original_product_data) {
    return json({ error: "Original product data is required." }, { status: 400 });
  }

  const model = genAI.getGenerativeModel({
    model: "gemini-2.5-flash",
    generationConfig: {
      temperature: 0.2,
      responseMimeType: "application/json",
    },
  });

  const prompt = `
  You are an expert e-commerce specialist, SEO strategist, and content writer. Your task is to meticulously analyze and, if necessary, rewrite a Shopify product's data to be fully optimized for e-commerce best practices, focusing *exclusively* on product-level attributes. Do NOT include any store-level or account-level issues (e.g., shipping, tax, payment, website-wide policies) in your analysis or suggestions.

  You will be provided with two key pieces of information:

  Original Product Data: A JSON object containing the current product's details.

  Analysis Report (Optional): A JSON object containing a detailed list of issues and suggestions. If this is empty or not provided, your first task is to perform a detailed analysis of the product based on the original data, identifying every possible product-specific issue related to Google Merchant Center, SEO, and Google Ads.

  Your goal is to use this information to generate a new, optimized version of the product's data.

  **Specific Instructions for Rewriting and Analysis:**

  **Conditional Logic:**
  -   If a \`gemini_analysis\` object is provided, use it directly to guide your rewriting.
  -   If no \`gemini_analysis\` is provided, perform a full product-level analysis first. Your analysis must be exhaustive and identify all product-specific issues and suggestions before you begin rewriting.

  **Crucial Rule for Rewriting:**
  -   **Only rewrite fields that are identified as having issues or needing improvement** based on the analysis (either provided via \`gemini_analysis\` or generated by you). If a field is already optimized and compliant with Google Merchant Center policies and SEO best practices, **you MUST retain its original value**. Do not make unnecessary changes to already optimized fields.

  **Rewriting Guidelines for Problematic Fields (Apply ONLY if a field needs improvement):**
  -   **Rewrite the Title:**
      -   The new title must be SEO-friendly, descriptive, and engaging.
      -   Incorporate relevant keywords and accurately reflect the product.
      -   **Strictly adhere to Google Merchant Center guidelines:** The title's length must be between 60 and 70 characters for optimal SEO display. Avoid keyword stuffing, excessive capitalization, and promotional text.
      -   **Crucially, the title must include essential product attributes such as brand, product type, model, color, and minimum key features** to ensure uniqueness, prevent duplicate issues, and enhance specificity for search engines and Google Merchant Center.
  -   **Rewrite the Description:**
      -   The new description must be highly detailed, compelling, and very well-structured.
      -   Use clear and logical headings (e.g., \`### Key Features\`, \`### Benefits\`, \`### What's Included\`, \`### Compatibility\`, \`### Why Choose This Product?\`).
      -   Utilize bullet points (\`*\`) for lists of features, benefits, or specifications.
      -   Break down text into concise, readable paragraphs.
      -   Highlight key features, benefits, use cases, and include a clear, persuasive call-to-action.
      -   Ensure the language is persuasive and addresses all relevant issues raised in the \`suggestions_for_sales_improvement\` from the analysis report.
      -   **Use Markdown for all formatting** (e.g., \`**bold**\`, \`*italic*\`, \`### heading\`, \`* bullet points\`).
      -   Minimum recommended length: 150 words for comprehensive SEO.
  -   **Create a New Handle:**
      -   The new handle (URL slug) must be SEO-friendly.
      -   It should be lowercase, use hyphens as separators, and contain the most important keywords from the new title.
      -   Avoid excessively long handles (ideally under 60 characters).
      -   **Must include essential product identifiers like brand, model, and color** to ensure uniqueness and SEO relevance.
  -   **Rewrite the Meta Description:**
      -   The new meta description should be a concise summary of the product.
      -   **Strictly adhere to SEO guidelines:** The meta description's length must be between 150 and 160 characters strictly for optimal search engine results page (SERP) display. It absolutely must not exceed 160 characters.
      -   It must be unique, compelling, include a primary keyword and a clear call-to-action to encourage clicks from search results.
      -   Must NOT be a direct copy of the product description.
  -   **Determine Google Product Category, Color, Material, and Condition:**
      -   Based on the product data, determine the most accurate \`google_product_category\`. Use the official Google Product Taxonomy.
      -   Identify the primary \`color\` of the product.
      -   Identify the primary \`material\` of the product.
      -   Determine the \`condition\` of the product (e.g., "new", "used", "refurbished").
  -   **Find the GTIN:**
      -   Based on the original product data and your extensive e-commerce knowledge, attempt to identify the GTIN (Global Trade Item Number) for this product.
      -   If you find a valid GTIN, include it in the output. If you are unable to find or determine a valid GTIN, set the value to \`null\`. Do not invent a GTIN.
  -   **Determine the Brand:**
      -   Based on the product's title and your extensive e-commerce knowledge, identify the brand of the product.
      -   If the brand is clearly identifiable, include it in the output. If you are unable to determine the brand, set the value to \`null\`.
  -   **Generate Tags:**
      -   Based on the product's type, brand name, model, and the provided \`existing_tags\`, generate a concise list of highly relevant tags.
      -   **Crucially, avoid generating tags that are repetitive or too similar to the \`existing_tags\` or to the product's core attributes (size, model, brand, type, color).** Focus on adding new, valuable, and non-redundant tags. 
      -   Also if there are tags already against that product that covers Size, Model, Brand, Type, Color then dont generate new tags and instead return blank or null for tags, but if the product doesn't have those tags covered or dont have any tags or have very less tags then please do generate the tags covering all those points and send it back.
      -   These tags should help categorize the product and improve its discoverability.
      -   Ensure the tags are applicable to all types of products for multiple users.
  -   **Pricing:**
      -   Ensure the new output includes the \`price\` and \`compareAtPrice\` from the original product data.
      -   The \`compareAtPrice\` must be greater than the \`price\` to indicate a sale. This is a critical Google Merchant Center requirement.

  Input Data:

  \`\`\`json
  {
  "original_product_data": ${JSON.stringify(original_product_data, null, 2)},
  "gemini_analysis": ${gemini_analysis ? JSON.stringify(gemini_analysis, null, 2) : 'null'},
  "existing_tags": ${JSON.stringify(original_product_data.tags || [], null, 2)}
  }
  \`\`\`

  Output Format:

  Your entire response must be a single JSON object. The object must contain the following keys: id, product_name, title, description, handle, meta_description, gtin, brand, price, compareAtPrice, google_product_category, color, material, condition, tags, and a new object called analysis_summary that contains a list of resolved_issues and a list of pending_issues_for_manual_fix.

  resolved_issues: An array of strings describing the issues that were successfully addressed by the rewrite.

  pending_issues_for_manual_fix: An array of objects. Each object must contain a message (the issue that could not be fixed automatically) and manual_fix_steps (a string with clear, concise steps on how to fix it manually).

  Example of the expected JSON output format:

  \`\`\`json
  {
  "id": "12345",
  "product_name": "Original Product Title",
  "title": "New Optimized Product Title with Keywords",
  "description": "### Key Features\\n* Feature 1\\n* Feature 2\\n\\nBenefits:\\n\\nThis is a compelling and detailed description...",
  "handle": "new-optimized-product-title-with-keywords",
  "meta_description": "A new and improved meta description must be between 150 and 160 characters strictly to entice clicks from search results.",
  "gtin": "1234567890123",
  "price": 49.99,
  "compareAtPrice": 59.99,
  "google_product_category": "Electronics > Audio > Audio Players & Recorders",
  "color": "Black",
  "material": "Plastic",
  "condition": "new",
  "tags": ["tag1", "tag2", "tag3"], // Example tags
  "analysis_summary": {
  "resolved_issues": [
  "The product description was rewritten to be more compelling and SEO-friendly.",
  "The URL handle was made lowercase and hyphenated for better SEO.",
  "The meta description was updated to be under 160 characters with a call-to-action."
  ],
  "pending_issues_for_manual_fix": [
  {
  "message": "The product images are low-resolution and will be rejected by Google Merchant Center.",
  "manual_fix_steps": "Please upload high-resolution images (at least 500x500 pixels) and a main product image with a solid white background."
  }
  ]
  }
  }
  \`\`\`
  `;

  try {
    const aiResponseText = await retryOperation(async () => {
      const result = await Promise.race([
        model.generateContent(prompt),
        new Promise((_, reject) =>
          setTimeout(() => reject(new Error('AI response timed out')), 120000) // 2 minutes timeout
        ),
      ]);
      const response = await (result as any).response;
      return response.text();
    }, 5, 1000, original_product_data.id); // 5 retries, 1 second initial delay

    const startIndex = aiResponseText.indexOf('{');
    const endIndex = aiResponseText.lastIndexOf('}');
    const jsonString = aiResponseText.substring(startIndex, endIndex + 1);
    
    const aiResponse = JSON.parse(jsonString);

    if (aiResponse.description) {
      aiResponse.description = await convertMarkdownToHtml(aiResponse.description);
    }

    return json({
      success: true,
      message: "Product auto-fix analysis complete.",
      rewrittenData: aiResponse,
    });

  } catch (error: any) {
    console.error("Error during auto-fix process:", error);
    return json({ error: `Auto-fix failed: ${error.message}` }, { status: 500 });
  }
}
