import { type LoaderFunctionArgs } from "@remix-run/node";
import { authenticate } from "../shopify.server";
import prisma from "../db.server";
import * as XLSX from "xlsx";

function severityColor(s: string) {
  if (s === "High") return "#d72c0d";
  if (s === "Medium") return "#b98900";
  return "#637381";
}

function severityBg(s: string) {
  if (s === "High") return "#fef2f2";
  if (s === "Medium") return "#fffbeb";
  return "#f0f9ff";
}

// ── Excel builder ────────────────────────────────────────────────────────────

function buildExcel(scan: any): Buffer {
  const result = scan.result as any;
  const summary = result?.scan_summary || {};
  const wb = XLSX.utils.book_new();

  // Summary sheet
  const summaryData = [
    ["Store GMC Compliance Report"],
    [],
    ["Store URL", summary.store_url || ""],
    ["Overall Risk", summary.overall_risk || ""],
    ["Pages Scanned", summary.pages_scanned ?? ""],
    ["Missing Required Pages", summary.pages_missing ?? ""],
    ["Broken Links Found", summary.broken_links_found ?? ""],
    ["Scan Date", new Date(scan.updatedAt).toLocaleString()],
    ["Generated By", "ShopFlix AI"],
  ];
  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
  summarySheet["!cols"] = [{ wch: 28 }, { wch: 50 }];
  XLSX.utils.book_append_sheet(wb, summarySheet, "Summary");

  // Helper to build an issue sheet
  const addIssueSheet = (sheetName: string, issues: any[], isMissingPages = false, isBrokenLinks = false) => {
    const headers = ["#", "Severity", "Issue Description", "Suggested Fix", "Fix Steps", "Auto Fixable", "Auto Fix Type", "Credit Cost"];
    if (isMissingPages) {
      headers.splice(2, 0, "Page Label", "URL");
    }
    if (isBrokenLinks) {
      headers.splice(2, 0, "URL");
    }

    const rows: any[][] = [headers];

    (issues || []).forEach((issue: any, i: number) => {
      const steps = Array.isArray(issue.detailed_fix_steps)
        ? issue.detailed_fix_steps.join("\n")
        : (issue.detailed_fix_steps || "");

      if (isMissingPages) {
        rows.push([
          i + 1,
          issue.severity || "",
          issue.label || "",
          issue.url || "",
          issue.suggested_fix || "",
          steps,
          issue.auto_fixable ? "Yes" : "No",
          issue.auto_fix_type || "",
          issue.credit_cost ?? "",
        ]);
      } else if (isBrokenLinks) {
        rows.push([
          i + 1,
          issue.severity || "High",
          issue.url || "",
          issue.suggested_fix || "",
          steps,
          issue.auto_fixable ? "Yes" : "No",
          issue.auto_fix_type || "",
          issue.credit_cost ?? "",
        ]);
      } else {
        rows.push([
          i + 1,
          issue.severity || "",
          issue.issue_description || "",
          issue.suggested_fix || "",
          steps,
          issue.auto_fixable ? "Yes" : "No",
          issue.auto_fix_type || "",
          issue.credit_cost ?? "",
        ]);
      }
    });

    const sheet = XLSX.utils.aoa_to_sheet(rows);
    sheet["!cols"] = [
      { wch: 4 }, { wch: 10 }, { wch: 50 }, { wch: 50 }, { wch: 60 }, { wch: 14 }, { wch: 18 }, { wch: 12 },
    ];
    XLSX.utils.book_append_sheet(wb, sheet, sheetName);
  };

  addIssueSheet("GMC Compliance", result?.merchant_center_compliance || []);
  addIssueSheet("Customer Trust & Policy", result?.customer_trust_and_policy || []);
  addIssueSheet("Site Structure & SEO", result?.site_structure_and_seo || []);
  addIssueSheet("Missing Pages", result?.missing_pages || [], true);
  addIssueSheet("Broken Links", result?.broken_links || [], false, true);

  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
}

// ── PDF (HTML) builder ───────────────────────────────────────────────────────

function badge(severity: string) {
  return `<span style="display:inline-block;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;background:${severityBg(severity)};color:${severityColor(severity)};border:1px solid ${severityColor(severity)}20">${severity}</span>`;
}

function issuesHtml(issues: any[], isMissingPages = false, isBrokenLinks = false): string {
  if (!issues?.length) {
    return `<p style="color:#12a04a;margin:0;font-size:14px">✓ No issues found in this category.</p>`;
  }
  return issues.map((issue: any, i: number) => {
    const sev = issue.severity || (isBrokenLinks ? "High" : "Medium");
    const desc = isMissingPages
      ? `<strong>${issue.label}</strong> — <a href="${issue.url}" style="color:#006ECB">${issue.url}</a>`
      : isBrokenLinks
      ? `<a href="${issue.url}" style="color:#006ECB">${issue.url}</a>`
      : (issue.issue_description || "");

    const steps = Array.isArray(issue.detailed_fix_steps) && issue.detailed_fix_steps.length
      ? `<ol style="margin:8px 0 0 0;padding-left:20px;color:#444;font-size:13px;line-height:1.7">${issue.detailed_fix_steps.map((s: string) => `<li>${s}</li>`).join("")}</ol>`
      : "";

    const autoFixBadge = issue.auto_fixable
      ? `<span style="display:inline-block;margin-left:8px;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:600;background:#eff6ff;color:#1d4ed8;border:1px solid #bfdbfe">⚡ Auto-fixable (${issue.credit_cost ?? "?"} credits)</span>`
      : "";

    return `
      <div style="border-left:3px solid ${severityColor(sev)};padding-left:14px;margin-bottom:18px;page-break-inside:avoid">
        <div style="display:flex;align-items:flex-start;gap:8px;flex-wrap:wrap;margin-bottom:6px">
          ${badge(sev)}
          ${autoFixBadge}
          <span style="font-size:14px;color:#212121;font-weight:600;flex:1">${desc}</span>
        </div>
        ${issue.suggested_fix ? `<p style="margin:0 0 6px 0;font-size:13px;color:#555;line-height:1.5">💡 ${issue.suggested_fix}</p>` : ""}
        ${steps}
      </div>
    `;
  }).join("");
}

function sectionHtml(title: string, issues: any[], isMissingPages = false, isBrokenLinks = false): string {
  if (!issues?.length) return "";
  return `
    <div style="background:#fff;border-radius:8px;border:1px solid #e5e7eb;padding:24px;margin-bottom:20px;page-break-inside:avoid">
      <h3 style="margin:0 0 16px 0;font-size:17px;font-weight:700;color:#212121;border-bottom:1px solid #f0f0f0;padding-bottom:10px">${title}</h3>
      ${issuesHtml(issues, isMissingPages, isBrokenLinks)}
    </div>
  `;
}

function buildPdfHtml(scan: any): string {
  const result = scan.result as any;
  const summary = result?.scan_summary || {};
  const risk = summary.overall_risk || "Medium";
  const riskColor = risk === "High" ? "#d72c0d" : risk === "Medium" ? "#b98900" : "#12a04a";
  const scanDate = new Date(scan.updatedAt).toLocaleString();

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Store GMC Compliance Report — ${summary.store_url || ""}</title>
  <style>
    * { box-sizing: border-box; }
    body {
      margin: 0;
      padding: 0;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      background: #f4f6f8;
      color: #212121;
    }
    .container { max-width: 860px; margin: 0 auto; padding: 24px 20px 48px 20px; }
    .print-btn {
      display: block;
      margin: 0 auto 20px auto;
      padding: 10px 28px;
      background: #1a4a5a;
      color: white;
      border: none;
      border-radius: 6px;
      font-size: 15px;
      font-weight: 600;
      cursor: pointer;
      text-align: center;
    }
    @media print {
      body { background: #fff; }
      .print-btn { display: none !important; }
      .container { max-width: 100%; padding: 0; }
      .page-break { page-break-before: always; }
    }
  </style>
</head>
<body>
  <div class="container">
    <button class="print-btn" onclick="window.print()">🖨️ Print / Save as PDF</button>

    <!-- Header -->
    <div style="background:linear-gradient(135deg,#1a4a5a 0%,#2A5B6D 100%);border-radius:10px;padding:28px;margin-bottom:20px;text-align:center;color:white">
      <div style="font-size:40px;margin-bottom:8px">🛡️</div>
      <h1 style="margin:0;font-size:24px;font-weight:700">Store GMC Compliance Report</h1>
      <p style="margin:8px 0 0 0;opacity:0.85;font-size:14px">${summary.store_url || ""}</p>
      <p style="margin:4px 0 0 0;opacity:0.7;font-size:13px">Generated by ShopFlix AI · ${scanDate}</p>
    </div>

    <!-- Summary -->
    <div style="background:#fff;border-radius:8px;border:1px solid #e5e7eb;padding:24px;margin-bottom:20px">
      <div style="display:flex;align-items:center;gap:12px;margin-bottom:18px;flex-wrap:wrap">
        <h3 style="margin:0;font-size:18px;font-weight:700">Scan Summary</h3>
        <span style="padding:4px 12px;border-radius:4px;font-size:13px;font-weight:700;color:${riskColor};border:1px solid ${riskColor};background:${severityBg(risk)}">${risk} Risk</span>
      </div>
      <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:16px">
        ${[
          { label: "Pages Scanned", value: summary.pages_scanned ?? "—", critical: false },
          { label: "Missing Pages", value: summary.pages_missing ?? "—", critical: (summary.pages_missing ?? 0) > 0 },
          { label: "Broken Links", value: summary.broken_links_found ?? "—", critical: (summary.broken_links_found ?? 0) > 0 },
        ].map(item => `
          <div style="background:#f9fafb;border-radius:6px;padding:14px">
            <p style="margin:0 0 6px 0;font-size:11px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:0.5px">${item.label}</p>
            <p style="margin:0;font-size:24px;font-weight:700;color:${item.critical ? "#d72c0d" : "#212121"}">${item.value}</p>
          </div>
        `).join("")}
      </div>
    </div>

    ${result?.missing_pages?.length ? sectionHtml("Missing Required Pages", result.missing_pages, true) : ""}
    ${result?.broken_links?.length ? sectionHtml("Broken Links", result.broken_links, false, true) : ""}

    <div class="page-break"></div>
    ${sectionHtml("Google Merchant Center Compliance", result?.merchant_center_compliance || [])}
    ${sectionHtml("Customer Trust & Policy Pages", result?.customer_trust_and_policy || [])}
    ${sectionHtml("Site Structure & SEO", result?.site_structure_and_seo || [])}

    <p style="text-align:center;font-size:12px;color:#9ca3af;margin-top:32px">
      Generated by ShopFlix AI Store GMC Compliance Scanner
    </p>
  </div>

  <script>
    // Auto-print when page loads (most browsers will show Save as PDF dialog)
    window.addEventListener('load', function() {
      setTimeout(function() { window.print(); }, 500);
    });
  </script>
</body>
</html>`;
}

// ── Loader ───────────────────────────────────────────────────────────────────

export async function loader({ request }: LoaderFunctionArgs) {
  const { session } = await authenticate.admin(request);
  if (!session) {
    return new Response("Unauthorized", { status: 401 });
  }

  const url = new URL(request.url);
  const format = url.searchParams.get("format") || "excel";
  const scanId = url.searchParams.get("scanId");

  // Load scan
  let scan: any;
  try {
    scan = scanId
      ? await (prisma as any).storeScan.findUnique({ where: { id: scanId } })
      : await (prisma as any).storeScan.findFirst({
          where: { shop: session.shop, status: "COMPLETE" },
          orderBy: { createdAt: "desc" },
        });
  } catch (e) {
    return new Response("Could not load scan data.", { status: 500 });
  }

  if (!scan) {
    return new Response("No completed scan found.", { status: 404 });
  }

  const storeUrl = scan.result?.scan_summary?.store_url || session.shop;
  const dateStr = new Date(scan.updatedAt).toISOString().split("T")[0];
  const safeStore = storeUrl.replace(/https?:\/\//, "").replace(/[^a-z0-9]/gi, "-");

  if (format === "excel") {
    const buffer = buildExcel(scan);
    return new Response(buffer, {
      status: 200,
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "Content-Disposition": `attachment; filename="compliance-report-${safeStore}-${dateStr}.xlsx"`,
        "Cache-Control": "no-cache",
      },
    });
  }

  // PDF → serve as HTML with print styles
  const html = buildPdfHtml(scan);
  return new Response(html, {
    status: 200,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="compliance-report-${safeStore}-${dateStr}.html"`,
      "Cache-Control": "no-cache",
    },
  });
}
